#!/usr/bin/env python
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import socket
import json

SERVER = "localhost"
PORT = 2947

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_socket.connect((SERVER, PORT))
client_socket.settimeout(2)

client_socket.send('?WATCH={"enable":true}')
client_socket.send('?POLL;')

def get_satellites(msg):
    sats_used = 0

    sats = msg['sky'][0]['satellites']
    for sat in sats:
        if sat['used'] == True:
            sats_used += 1

    return sats_used

message = ""
for tries in range(0,20,1):
    resp = client_socket.recv(2000)
    
    if '"POLL"' in resp:
        for line in resp.split():
            if 'POLL' in line:
                message = line
        break

client_socket.send('?WATCH={"enable":false}')
client_socket.close()

msg = json.loads(message)
print "<<<gpsd>>>"
print "mode:{}".format(msg['tpv'][0]['mode'])
print "hdop:{}".format(msg['sky'][0]['hdop'])
print "vdop:{}".format(msg['sky'][0]['vdop'])
print "sattelites:{}".format(len(msg['sky'][0]['satellites']))
print "sattelites_used:{}".format(get_satellites(msg))


